server:
  port: 9098

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: hotel-service
          uri: lb://hotel-service
          predicates:
            - Path=/api/hotel/**
