server:
  port: 9098

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: hotel-service
          uri: lb://hotel-service
          predicates:
            - Path=/api/hotel/**
        - id: destination-service
          uri: lb://destination-service
          predicates:
            - Path=/api/v1/destinations/**
        - id: file-service
          uri: lb://file-service
          predicates:
            - Path=/api/files/getMediaByEntity/**
        - id: trip-service
          uri: lb://trip-service
          predicates:
            - Path=/api/trips/**,/api/tripCategory/**,/api/user-trips/**
