
server:
  port: 9092

spring:
  application:
    name: user-service

  datasource:
    url: jdbc:postgresql://localhost:5432/trip_service
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  redis:
    host: localhost
    port: 6379
    timeout: 100ms
